ssl_certificate /etc/nginx/certs/k-project.com.pem;
ssl_certificate_key /etc/nginx/certs/k-project.com-key.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
